### ISSUE TITLE
Use token from git configuration if present

### ISSUE THREAD

**Issue by tehbilly** [firstrow/go-outdated#1]
Would prevent having to create an alias, and there's a precedent set for it already. See https://github.com/blog/180-local-github-config

**Comment by firstrow** [comment]
Good idea. Thanks.

**Comment by tehbilly** [comment]
No problem! This is a very well done little utility, and I like it. If I get some free time before you can implement this I'll see what I can throw together.

**Comment by firstrow** [comment]
Done.
